version: '3.8'

services:
  pipeline:
    build: .
    container_name: telco_pipeline
    volumes:
      - data_shared:/app/Data
      - reports_shared:/app/Reports
    # Ejecuta el pipeline de DataOps/MLOps
    command: ["uv", "run", "Scripts/Pipeline.py"]

  dashboard:
    build: .
    container_name: telco_dashboard
    ports:
      - "8501:8501"
    volumes:
      - data_shared:/app/Data
      - reports_shared:/app/Reports
    # Sobreescribimos el comando para levantar Streamlit apuntando a tu App.py
    command: ["uv", "run", "streamlit", "run", "Dashboard/App.py", "--server.port=8501", "--server.address=0.0.0.0"]
    depends_on:
      pipeline:
        condition: service_completed_successfully

volumes:
  data_shared:
  reports_shared: